---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend
  namespace: blog
  labels:
    app: blog-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-frontend
  template:
    metadata:
      namespace: blog
      labels:
        app: blog-frontend
    spec:
      containers:
        - name: blog-frontend
          image: cloud.canister.io:5000/saksmt/blog-frontend:$$VERSION$$
          ports:
            - containerPort: 80
