---
apiVersion: v1
kind: Service
metadata:
  name: blog-frontend
  namespace: blog
spec:
  selector:
    app: blog-frontend
  ports:
    - name: http
      port: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: blog-frontend
  namespace: blog
spec:
  host: blog-frontend
  subsets:
    - name: green
      labels:
        color: green
    - name: blue
      labels:
        color: blue
